//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTN_test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Job = new HashSet<Job>();
        }
    
        public int CaID { get; set; }
        public string CaName { get; set; }
        public string CaQName { get; set; }
        public string CaIcon { get; set; }
        public int CaOrder { get; set; }
    
        public virtual ICollection<Job> Job { get; set; }
    }
}
