//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTN_test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Job = new HashSet<Job>();
            this.Mailing = new HashSet<Mailing>();
        }
    
        public int CoID { get; set; }
        public string CoDName { get; set; }
        public string CoPwd { get; set; }
        public string CoGName { get; set; }
        public string CoGIcon { get; set; }
        public string CoGTel { get; set; }
        public string CoGUrl { get; set; }
    
        public virtual ICollection<Job> Job { get; set; }
        public virtual ICollection<Mailing> Mailing { get; set; }
    }
}
