//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTN_test.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CTNEntities1 : DbContext
    {
        public CTNEntities1()
            : base("name=CTNEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Award> Award { get; set; }
        public DbSet<Category> Category { get; set; }
        public DbSet<Certificate> Certificate { get; set; }
        public DbSet<Company> Company { get; set; }
        public DbSet<Hobbies> Hobbies { get; set; }
        public DbSet<InternshipExp> InternshipExp { get; set; }
        public DbSet<Job> Job { get; set; }
        public DbSet<Mailing> Mailing { get; set; }
        public DbSet<ProjectExp> ProjectExp { get; set; }
        public DbSet<Skill> Skill { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
