//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTN_test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hobbies
    {
        public int HID { get; set; }
        public int Uid { get; set; }
        public string Clike { get; set; }
        public string Cicon { get; set; }
        public int Corder { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
