//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTN_test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternshipExp
    {
        public int INID { get; set; }
        public int Uid { get; set; }
        public System.DateTime INtime { get; set; }
        public string Title { get; set; }
        public string Conten { get; set; }
        public int INorder { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
