//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTN_test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int JID { get; set; }
        public int Coid { get; set; }
        public int Caid { get; set; }
        public string JName { get; set; }
        public int Jquality { get; set; }
        public string Jsalary { get; set; }
        public string Jzdsaldw { get; set; }
        public string Jzdsaldy { get; set; }
        public string Jzgsaldy { get; set; }
        public System.DateTime ftime { get; set; }
        public System.DateTime Ptime { get; set; }
        public string Place { get; set; }
        public string Jrank { get; set; }
        public string JNrank { get; set; }
        public string Jdepict { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Company Company { get; set; }
    }
}
