//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTN_test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mailing
    {
        public int MID { get; set; }
        public int Mzt { get; set; }
        public System.DateTime Mtime { get; set; }
        public int Coid { get; set; }
        public int Uid { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Users Users { get; set; }
    }
}
