//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTN_test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Award = new HashSet<Award>();
            this.Certificate = new HashSet<Certificate>();
            this.Hobbies = new HashSet<Hobbies>();
            this.InternshipExp = new HashSet<InternshipExp>();
            this.Mailing = new HashSet<Mailing>();
            this.ProjectExp = new HashSet<ProjectExp>();
            this.Skill = new HashSet<Skill>();
        }
    
        public int UID { get; set; }
        public string UName { get; set; }
        public string UPwd { get; set; }
        public string UXName { get; set; }
        public string Uicon { get; set; }
        public string Sex { get; set; }
        public System.DateTime CStime { get; set; }
        public string Ujg { get; set; }
        public string UTel { get; set; }
        public string QQ { get; set; }
        public string WX { get; set; }
        public string Email { get; set; }
        public string WB { get; set; }
        public string XL { get; set; }
        public string School { get; set; }
        public string Vocational { get; set; }
        public string Qzyx { get; set; }
        public string Qwsal { get; set; }
        public string Evaluate { get; set; }
    
        public virtual ICollection<Award> Award { get; set; }
        public virtual ICollection<Certificate> Certificate { get; set; }
        public virtual ICollection<Hobbies> Hobbies { get; set; }
        public virtual ICollection<InternshipExp> InternshipExp { get; set; }
        public virtual ICollection<Mailing> Mailing { get; set; }
        public virtual ICollection<ProjectExp> ProjectExp { get; set; }
        public virtual ICollection<Skill> Skill { get; set; }
    }
}
